## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "false"
#canonifyURLs = "true"

# Local
baseURL = "https://lordlammington.github.io/TigridaWealth/"
publishDir = "public"
title = "Tigrida Wealth"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"
#Test
# Where The Fuck Are you getting pushed to?
## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------


[Params]

[Params.social]

[caches]
  [caches.images]
    dir = ':cacheDir/images'